#! bin/bash
echo "Checking if Homebrew package manager is installed..." if ! [ -x "$(command -v brew)" ]; then
echo -n "Homebrew not installed, install? (y/n)? "
read response
if [ "$response" != "${response#[Yy]}" ]; then
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" else
exit 1
fi
fi
echo "Homebrew installed"
echo "Performing GIT LFS install if necessary..."
brew install git-lfs
echo "GIT LFS installed"
echo "Cloning repository & ignoring LFS files"
GIT_LFS_SKIP_SMUDGE=1 git clone https://github.com/HarrisonEllerm/COSC345_SoftwareEngProj.git
cd COSC345_SoftwareEngProj
echo "Setting up LFS Hooks in repo and pulling LFS files"
git lfs install && git lfs pull
cd ..
echo "Installation finished OK"
